In [61]:
import sympy
import numpy

In [62]:
x1, x2 = sympy.symbols('x1 x2')

In [63]:
fx = x1 ** 2 + 2 * x1 * x2 + sympy.sin(x1) + 2

In [64]:
gradient_fx_1 = [sympy.diff(fx, var) for var in (x1, x2)]

In [65]:
gradient_fx_2 = sympy.hessian(fx, (x1, x2))

In [66]:
print("Đạo hàm bậc nhất của Fx: ")
for i, df in enumerate(gradient_fx_1, start=1):
    print(f"\u2202f/\u2202x{i} =", df)

Đạo hàm bậc nhất của Fx: 
∂f/∂x1 = 2*x1 + 2*x2 + cos(x1)
∂f/∂x2 = 2*x1


In [67]:
print("Đạo hàm bậc hai của Fx: ")
sympy.pprint(gradient_fx_2)

Đạo hàm bậc hai của Fx: 
⎡2 - sin(x₁)  2⎤
⎢              ⎥
⎣     2       0⎦


In [68]:
A = sympy.Matrix([[-1, 0, 1], [1, -1, 0]])
x = sympy.symbols('x')
Vx = A * x

In [69]:
gradient_Vx_1 = sympy.diff(Vx)

In [70]:
print("Đạo hàm bậc nhất của Vx:")
sympy.pprint(gradient_Vx_1)

Đạo hàm bậc nhất của Vx:
⎡-1  0   1⎤
⎢         ⎥
⎣1   -1  0⎦


In [71]:
# Chain Rule
# Đạo hàm bậc 1 : 
# Đạo hàm bậc 2 : 

x = sympy.symbols('x')
u = sympy.symbols('u')

# F(x) = x^2
Fx = x ** 2

# G(u) = sin(u)
Gu = sympy.sin(u)

# H(x) = G(F(x))
Hx = sympy.sin(Fx)

# Đạo hàm theo Chain Rule
gradient_Fx = sympy.diff(Fx, x) # F'(x)
gradient_Gu = sympy.diff(Gu, u) # G'(u), u = F(x)
gradient_Gx = gradient_Gu.subs(u, Fx) # G'(F(x))
gradient_Hx = gradient_Fx * gradient_Gx # H'(x) = F'(x) * G'(F(x))

# Hiển thị kết quả
print("F(x)    : ", Fx)
print("F'(x)   : ", gradient_Fx)
print("G(u)    : ", Gu)
print("G'(u)   : ", gradient_Gu)
print("G'(F(x)): ", gradient_Gx)
print("H(x)    : ", Hx)
print("H'(x)   : ", gradient_Hx)


F(x)    :  x**2
F'(x)   :  2*x
G(u)    :  sin(u)
G'(u)   :  cos(u)
G'(F(x)):  cos(x**2)
H(x)    :  sin(x**2)
H'(x)   :  2*x*cos(x**2)


In [90]:
# Ma trận A
A = numpy.array([[2, 3], [1, 4]])

In [91]:
# Ma trận đảo A
A_inv = numpy.linalg.inv(A)

In [92]:
# Kiểm tra tính khả nghịch của ma trận A và ma trận đảo của A
Y = numpy.int8(numpy.dot(A, A_inv))

In [153]:
X = numpy.array([[-2, -2], [-1, 4], [2, 3]])

In [185]:
# Cách tính ma trận hiệp phương sai không dùng hàm có sẵn
K = X.T
m = K.shape[0]
N = K.shape[1]

Mx = numpy.sum(K[0][:]) / N
My = numpy.sum(K[1][:]) / N
M = numpy.array([[Mx], [My]])

M2 = numpy.ones((m, N))

for i in range(m):
    for j in range(N):
        M2[i][j] = M[i] * 1

D = K - M2

cov1 = 1 / (N - 1) * numpy.dot(D, D.T)

print(cov1)

[[ 4.33333333  3.83333333]
 [ 3.83333333 10.33333333]]


C:\Users\phong.nguyen-thang\AppData\Local\Temp\ipykernel_1896\450849849.py:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  M2[i][j] = M[i] * 1


In [186]:
# Cách tính ma trận hiệp phương sai dùng hàm có sẵn
cov2 = numpy.cov(X.T)
print(cov2)

[[ 4.33333333  3.83333333]
 [ 3.83333333 10.33333333]]


In [1]:
import cv2

In [4]:
img = cv2.imread('girl.jpg')

In [6]:
rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

In [7]:
rgb_img

array([[[10, 12,  9],
        [11, 13, 10],
        [12, 14, 11],
        ...,
        [14, 14, 14],
        [15, 15, 15],
        [12, 12, 12]],

       [[10, 12,  9],
        [11, 13, 10],
        [12, 14, 11],
        ...,
        [14, 14, 14],
        [14, 14, 14],
        [12, 12, 12]],

       [[11, 13, 10],
        [11, 13, 10],
        [12, 14, 11],
        ...,
        [14, 14, 14],
        [14, 14, 14],
        [12, 12, 12]],

       ...,

       [[24, 18, 20],
        [23, 17, 19],
        [22, 18, 19],
        ...,
        [23, 29, 19],
        [24, 30, 18],
        [25, 31, 19]],

       [[24, 18, 20],
        [23, 17, 19],
        [22, 18, 19],
        ...,
        [23, 29, 19],
        [24, 30, 18],
        [25, 31, 19]],

       [[23, 17, 19],
        [25, 19, 21],
        [25, 21, 22],
        ...,
        [23, 29, 19],
        [22, 28, 16],
        [21, 27, 15]]], dtype=uint8)